version: 2.1

description: "Automatically builds and pushes Docker images."
display:
  source_url: "https://github.com/remind101/docker-build"

jobs:
  # build a docker image and push to docker hub and ECR
  build-push:
    parameters:
      checkout:
        description: >-
          If false, skip checking out the repository. This is useful when
          combined with pre-steps to use only workspace-attached files.
        type: "boolean"
        default: true
      build-args:
        description: >-
          Additional arguments to be passed to "docker build", e.g. "--target my-stage --build-arg FOO=42".
        type: "string"
        default: ""
    docker:
      - image: "{{docker_image}}"
    environment:
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: "plain"
    steps:
      - when:
          condition: << parameters.checkout >>
          steps:
            - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build, tag, and push to Docker Hub and AWS ECR
          command: docker-build << parameters.build-args >>
